# Generated by Django 5.1.7 on 2025-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avar_word', models.CharField(max_length=255, unique=True)),
                ('russian_translations', models.TextField()),
                ('english_translations', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
            ],
        ),
    ]
