# Generated by Django 5.1.7 on 2025-03-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('avar_word', models.CharField(max_length=255)),
                ('russian_translation', models.TextField()),
                ('english_translation', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
