# Generated by Django 5.1.7 on 2025-03-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0002_suggestedentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avar_word', models.CharField(max_length=255)),
                ('voice_file', models.FileField(upload_to='audio/')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
