# Generated by Django 5.1.7 on 2025-03-27 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0004_rename_examples_entry_example_alter_entry_avar_word_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioentry',
            old_name='voice_file',
            new_name='audio_file',
        ),
        migrations.RemoveField(
            model_name='audioentry',
            name='avar_word',
        ),
        migrations.AddField(
            model_name='audioentry',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictapp.entry'),
        ),
    ]
