# Generated by Django 5.2 on 2025-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0005_rename_voice_file_audioentry_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='example',
        ),
        migrations.AddField(
            model_name='entry',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
    ]
